steps:
  - command: pnpm build
    plugins:
      - seek-oss/docker-ecr-cache#v3.0.0:
          cache-on:
            - package.json # avoid cache hits on stale lockfiles
            - pnpm-lock.yaml
      - docker#v5.10.0:
          volumes:
            - /workdir/node_modules
  - command: echo "I will stick!"
    agents:
      hostname: "$BUILDKITE_AGENT_META_DATA_HOSTNAME"
  - command: |
      ls -la
      cd packages
      ls -la
      cd comfy-auth-util
      npm ci
      npm build