steps:
  - label: ":hammer: Build"
    command: "packages/comfy-auth-util/pipeline.sh"
    key: build
  - label: ":pencil: Test"
    command: bktec run
    plugins:
      - tests#v1.0.0:
          test-runner: vitest
          result-path: junit-*.xml
    parallelism: 4